# Generated by Django 4.2.13 on 2024-06-04 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud_mysql', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='titulo',
            new_name='title',
        ),
    ]
